sonar.projectKey=Francisco Javier Rosas Garcia_outline  
sonar.projectName=Francisco Javier Rosas Garcia
sonar.sources=server/utils
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/dist/**
sonar.tests=server/utils
sonar.test.inclusions=**/*.test.ts
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.node.maxspace=4096
