sonar.projectKey=outline-wiki
sonar.projectName=Outline Wiki
sonar.sources=server/utils
sonar.exclusions=**/node_modules/**, **/.yarn/**, **/build/**, **/dist/**, **/data/**, **/*.test.ts
sonar.tests=server/utils
sonar.test.inclusions=**/*.test.ts
sonar.python.coverage.reportPaths=proyecto_pruebas_e2e/coverage.xml
sonar.javascript.node.maxspace=4096